name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Testing:
    name: Build and Test Java v${{ matrix.java }} from ${{ matrix.java-distribution }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [8, 11, 17]
        java-distribution: [temurin, corretto, microsoft]
        exclude:
          - java: 8
            java-distribution: microsoft
          - java: 8
            java-distribution: temurin
            os: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5
      - name: Setup Java 8
        uses: actions/setup-java@v5
        with:
          distribution: ${{ matrix.java-distribution }}
          java-version: ${{ matrix.java }}
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build Java Code [Self]
        if: github.event.pull_request == null || github.event.pull_request.head.repo.full_name == github.repository
        run: ./gradlew build
        env:
          PGP_SIGNING_KEY: ${{ secrets.PGP_SIGNING_KEY }}
          PGP_SIGNING_PASSWORD: ${{ secrets.PGP_SIGNING_PASSWORD }}
      - name: Prepare building Java Code [Fork]
        if: github.event.pull_request != null && github.event.pull_request.head.repo.full_name != github.repository
        shell: bash
        run: |
          if [ $OS = 'macos-latest' ]; then
            sed -i '' 's/this.enabled = true/this.enabled = false/g' build.gradle.kts
          else
            sed -i 's/this.enabled = true/this.enabled = false/g' build.gradle.kts
          fi
        env:
          OS: ${{ matrix.os }}
      - name: Build Java Code [Fork]
        if: github.event.pull_request != null && github.event.pull_request.head.repo.full_name != github.repository
        run: ./gradlew build
