name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Testing:
    name: Testing with node v${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [8, 11, 17]
        java-distribution: [temurin, microsoft, corretto]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.java-distribution }}}
          java-version: ${{ matrix.java }}
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build
        run: gradle build

  CodeQL:
    name: Codequality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
